# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:lints/recommended.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Additional custom rules:
linter:
  rules:
    always_use_package_imports: true
    prefer_single_quotes: true
    avoid_redundant_argument_values: true
