name: date_checker
description: Convenient extension methods on DateTime plus other helpful utility methods.
version: 0.1.0
homepage: https://github.com/CalvinGonsalves/date_checker

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.17.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
