name: date_checker
description: Convenient extension methods on DateTime plus other helpful utility methods.
version: 1.0.0+1
homepage: https://github.com/CalvinGonsalves/date_checker

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.10
